name: Build and Deploy Docs

on:
  push:
    branches:
      - main # change if your default branch is different

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or the version you use

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Remove old docs directory
        run: rm -rf docs

      - name: Move build output to docs
        run: mv dist docs

      - name: Commit and push updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update docs after build [skip ci]" || echo "No changes to commit"
          git push
